export default {
  app_name: 'Car repair',
  login_title: 'Login',
  register_title: 'Register',
  username_hint: 'Your username',
  password_hint: 'password',
  confirm_password_hint: 'confirm password',
  dont_have_account_question: 'Don\'t have an account?',
  already_have_account_question: 'Already have an account?',
  login_button: 'Login',
  register_button: 'Register',
  logged_in_as: 'Logged in as: ',
  login_progress: 'Logging in...',
  no_response: 'there was no response from the server',
  invalid_request: 'invalid request',
  unauthorized: 'You are not authorized to do this operation',
  repairs_list_empty_message: 'There are no repairs matching your criteria',
  repairs_list_header: 'Today\'s repairs',
  filter_button: 'appliedFilters',
  filter_label_choose_day: 'Choose day',
  filter_label_choose_user: 'Choose user',
  filter_label_choose_time: 'Choose time',
  assign_user: 'Assign user',
  is_completed: 'Is completed',
  apply_button: 'Apply',
  filter_label_choose_status: 'Status',
  filter_completed_show_all: 'Show All',
  filter_completed_only: 'Completed only',
  filter_incomplete_only: 'Incomplete only',
  repairs_list_for: date => `Repairs for ${date}`,
  my_repairs_list_for: date => `My repairs for ${date}`,
  create_repair: 'Create repair',
  edit_repair: 'Edit repair',
  choose_time: 'Choose time',
  pending_completion_approval: 'Pending completion approval...',
  confirm_completed: 'Confirm completion',
  completed: 'Completed',
  comments: 'Comments',
  comment: 'Comment',
  comment_here_hint: 'Comment here',
  no_comments_yet: 'No comments yet',
  complete_repair_button: 'Complete repair',
  users_title: 'Users',
  user_wrote_format: username => `${username} wrote: `,
};
