export default {
  app_name: 'Car repair',
  login_title: 'Login',
  register_title: 'Register',
  username_hint: 'Your username',
  password_hint: 'password',
  confirm_password_hint: 'confirm password',
  dont_have_account_question: 'Don\'t have an account?',
  already_have_account_question: 'Already have an account?',
  login_button: 'Login',
  register_button: 'Register',
  logged_in_as: 'Logged in as: ',
  login_progress: 'Logging in...',
  no_response: 'there was no response from the server',
  invalid_request: 'invalid request',
  unauthorized: 'You are not authorized to do this operation',
  repairs_list_empt_message: 'There are no repairs planned for today',
  repairs_list_header: 'Today\'s repairs',

};
